### ISSUE TITLE
Unable to build without removing 'remove-project' element for platform/frameworks/testing

### ISSUE THREAD

**Issue by mikehardy** [Galaxy-J5/j5_local_manifest#1]
I attempted to use this local manifest to repo sync and then compile for j5nltexx, and was able to successfully repo sync and generate a ROM that runs, but only after removing the 'remove-project' element near the top for 'platform/frameworks/testing'

Until I commented that line out, I received this error when attempting to do a repo sync:

fatal: remove-project element specifies non-existent project: platform/frameworks/testing

**Comment by ganeshi4u** [comment]
Delete the folder(platform/frameworks/testing) manually from the source and then remove the line from local_manifest.xml .That frameworks folder causes build erros it's a well know issue with cm12.1 so there's no harm in removing it.

**Comment by mikehardy** [comment]
Okay - I commented out the line and was successful as mentioned, but it was a hard-stop error. For any future inexperienced folks, might be good to put a comment on top of the line in the file indicating it's safe to comment out / delete? I'd propose a patch and attach a diff normally but seems like overkill for a comment :). Thanks Ganesh

**Comment by nikolaoskalomiris** [comment]
Marking this issue as solved. CyanogenMod has removed by default this repository on cm-12.1 builds.
